/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUser: typeof import('./src/components/AddUser.vue')['default']
    AlertView: typeof import('./src/components/AlertView.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    copy: typeof import('./src/components/EditUserView copy.vue')['default']
    CreateOrderView: typeof import('./src/components/CreateOrderView.vue')['default']
    CreateUserView: typeof import('./src/components/CreateUserView.vue')['default']
    EditOrderView: typeof import('./src/components/EditOrderView.vue')['default']
    EditUserView: typeof import('./src/components/EditUserView.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    OrdersView: typeof import('./src/components/OrdersView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestAlertView: typeof import('./src/components/TestAlertView.vue')['default']
    UsersView: typeof import('./src/components/UsersView.vue')['default']
  }
}
